== Физическое моделирование
В данной технологии рассматривается физическое моделирование схемы

=== Определение
Физическое моделирвание в разработке - это создание и анализ физической модели продукта, которая либо максимально приближенна по работе к конечному продукту но реализовано на гибкой платформе, либо кострукционно максимально приближенно к продукту. Обычно оно к нему прибегают, когда пограмное моделирование исчерпывает себя.

=== Примеры
Ярким примером может послужить физическое моделирование в цикле разработки процессоров.

* Первый этап моделирования - это создание модели на FPGA, как на дорогой, но очень гибкой платформе. Это дешевле, чем каждый раз производить новый процессор. Данное моделирование применяется т.к. програмное моделирование процессора целиком на сложных задачах слишком тяжела.

* Второй этап моделирования - это прототипирование на кристале. Физика создания пооцесоров крайне сложна и перед массовым производством их нужно тщательно проверить на корректность работы схемы.

=== Физическое моделирование в данной работе

Вданной работе присутствует только первый этап физического моделирования. Для этого используется макетная плата и реальные компоненты (см изображение).
При этом выбраны следующие характеристики схемы:

* C~1~ =
* C~2~ =
* R~1~ =
* R~2~ =

Данная комбинация параметров создаёт нестабильные колебания. Частота на одном светодиоде растёт, пока он не станет гореть постоянно, а у другого падает, пока он не потухнет.